// <auto-generated />
using System;
using Feed.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Feed.Migrations
{
    [DbContext(typeof(FeedContext))]
    [Migration("20190929232532_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Feed.Models.FeedItemModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Details");

                    b.Property<int?>("FeedModelId");

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.HasIndex("FeedModelId");

                    b.ToTable("FeedItemModel");
                });

            modelBuilder.Entity("Feed.Models.FeedModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.ToTable("FeedModel");
                });

            modelBuilder.Entity("Feed.Models.FeedItemModel", b =>
                {
                    b.HasOne("Feed.Models.FeedModel")
                        .WithMany("Items")
                        .HasForeignKey("FeedModelId");
                });
#pragma warning restore 612, 618
        }
    }
}
